export enum CART_TYPES {
  REMOVE_PRODUCT_CART = 'REMOVE_PRODUCT_CART',
  CREATE_PRODUCT_CART = 'CREATE_PRODUCT_CART',
  UPDATE_PRODUCT_CART = 'UPDATE_PRODUCT_CART',
  REMOVE_ALL_PRODUCT_CART = 'REMOVE_ALL_PRODUCT_CART',
}
