export enum STACK_SCREENS {
  HOME = 'STACK_HOME_VIEW',
  PRODUCT_DETAILS = 'STACK_PRODUCT_DETAILS_VIEW',
  CART = 'STACK_CART_VIEW',
  ORDER = 'STACK_ORDER_VIEW',
  ORDER_SUCCESS = 'STACK_ORDER_SUCCESS_VIEW',
}
